### ISSUE TITLE
Docs reference unavailable version

### ISSUE THREAD

**Issue by ChrisSargent** [simonireilly/observatory-github-action#318]
Hey the docs reference version `0.0.1` but this version is not available. thanks!

**Comment by simonireilly** [comment]
Thanks Chris, I will update the documentation.

I haven't been dilligent here and I appreciate your feedback.

**Comment by ChrisSargent** [comment]
no worries, thanks.

**Comment by simonireilly** [comment]
Fixing this today 👍
